version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    image: pihole/pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TIME_ZONE}
      WEBPASSWORD: ${PASSWORD}
      ServerIP: ${IP_ADDRESS}
    # Volumes store your data between container upgrades
    volumes:
      - "~/.pihole/etc-pihole/:/etc/pihole/"
      - "~/.pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
      # run `touch ~/.pihole/var-log/pihole.log` first unless you like errors
      - "~/.pihole/var-log/pihole.log:/var/log/pihole.log"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
  qbittorent:
    image: linuxserver/qbittorrent
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIME_ZONE}
      UMASK_SET: "022"
      WEBUI_PORT: "8080"
    volumes:
      - "~/.qbittorent/config:/config"
      - "~/Downloads:/downloads"
    restart: always
  samba:
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - WORKGROUP=workgroup
      - USER=${USERNAME};${PASSWORD}
      - RECYCLE=true
      - SHARE=Media;/mnt;yes;no;no;;${USERNAME}
    volumes:
      - ${MOUNT_POINT}:/mnt
    tmpfs:
      - /tmp
    read_only: true
    restart: always
